-- Persistent API keys for Mini AI-DOS.
--
-- NOT WIRED TO THE RUNTIME YET: the gateway currently authenticates
-- against the single MINI_AI_DOS_API_KEY environment variable. This
-- migration exists so the database phase starts from a reviewed,
-- security-correct schema (hash-only storage) the moment Postgres is
-- reachable — per specs/database/migrations-strategy.md: golang-migrate,
-- forward-only, one file per change.
--
-- Raw keys are NEVER stored. key_hash is the hex-encoded SHA-256 of
-- the raw key; key_prefix (first 8 chars) exists only so a human can
-- tell keys apart in a list.

CREATE TABLE IF NOT EXISTS api_keys (
    id          UUID PRIMARY KEY,                 -- UUIDv7, generated by the application
    key_hash    TEXT NOT NULL UNIQUE,             -- SHA-256 hex of the raw key
    key_prefix  TEXT NOT NULL,                    -- e.g. "mad_a1b2c" — identification only, not secret
    name        TEXT NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at  TIMESTAMPTZ                       -- revocation is a flag, never a row delete
);
